[book]
authors = ["Contributors from Piano VI's community"]
language = "en"
multilingual = false
src = "src"
title = "Piano-ing 101"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["theme/css/mdbook-admonish.css", "theme/css/sidebar-style.css"]
additional-js = ["theme/js/sidebar.js"]
