[book]
authors = ["aidswidjaja"]
language = "en"
multilingual = false
src = "src"
title = "Piano-ing 101"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
additional-css = ["mdbook-admonish.css"]
